export const labels = {
    pl: {
      about: "O nas",
      platforms: "Platformy przenośne",
      applications: "Zastosowanie",
      industries: "Branże",
      lifts: "Podnośniki",
      palletizer: "Paletyzator",
      contact: "Kontakt",
      headline: "Zaawansowane maszyny hydrauliczne",
      subheadline: "Specjalizacja w platformach hydraulicznych i podnośnikach",
      mainTitle:"PLATFORMY PODNOŚNE DLA WIĘKSZEGO BEZPIECZEŃSTWA I WYDAJNOŚCI",
      mainText:"Nasze zaawansowane niestandardowe podnośniki nożycowe zostały zaprojektowane i skonstruowane z myślą o wydajności i niezawodności. Dowiedz się, jak zaoszczędzić czas i koszty oraz zachować zdrowie i produktywność pracowników.",
      mainApplications:"ZASTOSOWANIA",
      mainText2: {
        usage: "ZASTOSOWANIE",
        platforms: "PLATFORM",
        lifting: "PODNOŚNYCH",
        hymo: "HYMO",
        text1: "Nasza koncepcja Vertical City integruje wiele naszych rozwiązań transportu pionowego w spójną całość.",
        text2:"Zobacz możliwości zastosowania naszych rozwiązań w produkcji i logistyce.",
        text3:"Obejrzyj filmy, aby zobaczyć je w akcji.",
        text4:"ZOBACZ FILM",
      },
      mainText3: {
        tables: "STOŁY PODNOŚNE",
        hymo: "HYMO",
        safety: "DO BEZPIECZNEGO",
        transport: "TRANSPORTU W PIONIE",
        text1: "Nasze produkty zapewniają sprawne działanie oraz bezpieczeństwo i zdrowie w miejscu pracy.",
        text2:"Nasze platformy podnośne charakteryzuje  niezawodność, wydajność i bezpieczeństwo.",
        text3:"Jesteśmy ekspertami technologii podnoszenia i mamy duże doświadczenie w projektowaniu i produkcji wytrzymałych, wysokowydajnych stołów podnośnych.",
      },
    },
    en: {
      about: "About us",
      platforms: "Portable platforms",
      applications: "Applications",
      industries: "Industries",
      lifts: "Lifts",
      palletizer: "Palletizer",
      contact: "Contact",
      headline: "Advanced Hydraulic Machinery",
      subheadline: "Specialized in Hydraulic Tables and Lifts",
      mainTitle:"ELEVATING PLATFORMS FOR ENHANCED SAFETY AND PRODUCTIVITY",
      mainText:"Our advanced, custom-designed scissor lifts are engineered for maximum efficiency and reliability. Learn how they help reduce time and costs while keeping your workers safe and productive.",
      mainApplications:"KEY APPLICATIONS",
      mainText2: {
        usage: "APPLICATIONS OF",
        platforms: "PLATFORMS",
        lifting: "LIFTING",
        hymo: "HYMO",
        text1: "Our Vertical City concept integrates multiple vertical transport solutions into a cohesive system.",
        text2: "Discover how our solutions can enhance manufacturing and logistics operations.",
        text3: "Watch the videos to see them in action.",
        text4: "WATCH VIDEO",
    },
      mainText3: {
        tables: "LIFT TABLES",
        hymo: "HYMO",
        safety: "FOR SAFE",
        transport: "VERTICAL TRANSPORT",
        text1: "Our products ensure smooth operation, workplace safety, and employee health.",
        text2: "Our lifting platforms are defined by reliability, efficiency, and safety.",
        text3: "We are lifting technology experts with extensive experience in designing and manufacturing durable, high-performance lift tables.",
      },

    },
  };